name: Cypress Tests
on: 
  workflow_dispatch:
  push:
    paths:
      - src/*
      - cypress/*
      - _webpack/*
      - _public/*
      - cypress.json
    branches:
      - master
      - release/*
  pull_request:
    paths:
      - src/*
      - cypress/*
      - _webpack/*
      - _public/*
      - cypress.json
    branches:
      - master
      - release/*
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn cypress run-ct
